repos:
  # from odoo/upgrade
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-logging-format
          - flake8-implicit-str-concat
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: check-xml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-symlinks
    - id: debug-statements
  # from OCA
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.5.3
    hooks:
      - id: pylint
        name: pylint with optional checks
        args: ["--rcfile=.pylintrc", "--exit-zero"]
        verbose: true
        additional_dependencies: ["pylint-odoo==3.5.0"]
        exclude: templates/static/util.py
      - id: pylint
        name: pylint with mandatory checks
        args: ["--rcfile=.pylintrc-mandatory"]
        additional_dependencies: ["pylint-odoo==3.5.0"]
        exclude: templates/static/util.py
  # TODO Avoid awebdeveloper/pre-commit-prettier if possible
  # HACK https://github.com/prettier/prettier/issues/7407
  - repo: https://github.com/awebdeveloper/pre-commit-prettier
    rev: v0.0.1
    hooks:
      - id: prettier
        name: prettier xml plugin
        additional_dependencies:
          - "prettier@1.19.1"
          - "@prettier/plugin-xml@0.7.2"
        files: \.xml$
